version: '2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: node_modules/.bin/nodemon --exec npm start
    environment:
      NODE_ENV: development
    ports:
      - 80:80
      - 3000:3000
    volumes:
     - .:/home/app/web
     - /home/app/web/node_modules
  mongo:
    image: mongo:3.3.15
    ports:
      - 27017:27017
    volumes:
      - ./db/mongo:/data/db
  neo4j:
    image: neo4j:3.0.6
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./db/neo4j:/data
